### ISSUE TITLE
Arrays as params are not supported

### ISSUE THREAD

**Issue by Pzixel** [paritytech/pwasm-abi#56]
Sample contract:

```rust
#[eth_abi(TokenEndpoint, TokenClient)]
pub trait SampleContractInterface {
  fn constructor(&mut self);
  fn createRequest(&mut self, serviceNumber: [u8; 30], date: u64);
}

pub struct SampleContract;

impl SampleContractInterface for SampleContract {
	fn constructor(&mut self) {}

	fn createRequest(&mut self, serviceNumber: [u8; 30], date: u64) {}
}
```

All tests are passing, but when it's called via `web3` api it returns an error.

Logs don't provide a lot of information, however I post them too

```json
{
  "transactionHash": "0xeb0885071aa00c8ec9c6df9620af67c22aa0012daef881f607bc5c8a4df8534c",
  "transactionIndex": "0x0",
  "blockHash": "0xe5f5d1018bbcf228695c8cfcd7f548f434384df6a4e0ee5bfba44b488d93d22e",
  "blockNumber": "0x5d47",
  "cumulativeGasUsed": "0x4630c0",
  "gasUsed": "0x4630c0",
  "contractAddress": null,
  "status": "0x0",
  "logs": []
}
```

I expect it to be working via web3 calls.

**Comment by fckt** [comment]
There is no AbiType imp for fixed sized arrays (see https://github.com/paritytech/pwasm-abi/blob/master/src/eth/common.rs).. In tests you pass decoded values to the contract methods, there is no need for decoding in tests. Obviously we need to implement AbiType for fixed-sized arrays as well.

**Comment by fckt** [comment]
Yeah, it seems there is a bug in the implementation. Fixed-size array elements should have left-aligned padding. The source of confusion I guess is that elements in a non-fixed-size arrays have a right-aligned padding.

From the spec:

```
bytes, of length k (which is assumed to be of type uint256):

enc(X) = enc(k) pad_right(X), i.e. the number of bytes is encoded as a uint256 followed by the actual value of X as a byte sequence, followed by the minimum number of zero-bytes such that len(enc(X)) is a multiple of 32.
```

```
bytes<M>: enc(X) is the sequence of bytes in X padded with zero-bytes to a length of 32.
```

Also `ethereumjs-abi` implementation proves that there is no right-padding for fixed-size arrays:
https://github.com/ethereumjs/ethereumjs-abi/blob/master/lib/index.js#L135

In contrast with a non-fixed-size arrays:
https://github.com/ethereumjs/ethereumjs-abi/blob/master/lib/index.js#L142

**Comment by fckt** [comment]
https://github.com/paritytech/pwasm-abi/pull/57

**Comment by fckt** [comment]
@Pzixel does that solved your issue?

**Comment by Pzixel** [comment]
I currently cannot confirm it now, but i'l check it tomorrow. Great work.

**Comment by Pzixel** [comment]
Yes, it did. Please, bump version so I can fetch it from crates.io

**Comment by NikVolf** [comment]
it was published already, do `cargo update -p pwasm-abi`

**Comment by Pzixel** [comment]
I'm pretty sure that there wasn't `ba9ffa3` when I wrote this. Anyway, thank you for bumping!
