### ISSUE TITLE
Failed to run cargo test

### ISSUE THREAD

**Issue by ztou** [paritytech/pwasm-abi#61]
~/dapp/wasm/pwasm-abi > cargo test                                                                                         
```
   Compiling pwasm-abi v0.1.4 
error[E0463]: can't find crate for `hex`========================>      ] 10/11: pwasm-abi
 --> src/eth/tests.rs:1:1
  |
1 | extern crate rustc_hex as hex;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `pwasm-abi`.

To learn more, run the command again with --verbose.
```

I can't change the optional to false in the Cargo.toml, there will be another issue.
> rustc-hex = { version = "1.0", optional = true }

I just get start with pwasm-abi, any hint to fix the test issue?

**Comment by Pzixel** [comment]
1. Now testing should run on defaults (fixed in #60 )
1. To run the full stuide you should use `cargo test--features std` or `cargo test--features test` (the latter for `tests` folder).

**Comment by fckt** [comment]
@ztou did it help?

**Comment by ztou** [comment]
@fckt : thanks, it works!
