### ISSUE TITLE
cannot find type `Vec` in this scope

### ISSUE THREAD

**Issue by dforsten** [paritytech/pwasm-abi#79]
Using version 0.2 of pwasm-abi-derive like this:

```
#[eth_abi(TokenEndpoint)]
pub trait TokenInterface {
    /// The constructor
    fn constructor(&mut self, _total_supply: U256);
    /// Total amount of tokens
    fn totalSupply(&mut self) -> U256;
}
```

Will result in the following error on build (using nightly-2018-11-12):

```
error[E0412]: cannot find type `Vec` in this scope
```

The following line in lib.rs of pwasm-abi-derive seems to be the culprit:
```
use pwasm_abi::types::{H160, H256, U256, Address};
```

Changing it to include "Vec":
```
use pwasm_abi::types::{H160, H256, U256, Address, Vec};
```
fixes the build.

**Comment by fckt** [comment]
It happens in the `no-std` mode only, right? I don't see any other way on how to fix this except to add `Vec` import into `pwasm-abi-derive`..

Related question, just in case: does everyone knows how the `[features] section` plays with a `proc-macro = true`?
