### ISSUE TITLE
Payable functions do not have payable set in JSON ABI

### ISSUE THREAD

**Issue by danrobdean** [paritytech/pwasm-abi#86]
When building a smart contract with a function marked with #[payable], the ABI JSON output by the build does not set payable to true.
Manually editing the JSON after the build seems to give the expected results, but this is quite cumbersome.

As you can see, the commit in which the payable attribute was added ([here](https://github.com/paritytech/pwasm-abi/commit/e14c00d8d0e096d4609ec9c0c2b5b9c4358dd02d)) did not modify the JSON generation to include the payable attribute.

**Comment by NikVolf** [comment]
Thanks for report, fix is on it's way!
